"""Add broker trade daily and watchlist tables

Revision ID: 2bce83dc4821
Revises: f71aee9282b2
Create Date: 2025-08-14 01:42:13.031632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2bce83dc4821"
down_revision: Union[str, None] = "f71aee9282b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_trade_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_symbol", sa.String(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column(
            "broker_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "broker_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("buy_volume", sa.BIGINT(), nullable=True),
        sa.Column("sell_volume", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_symbol"],
            ["stocks.stock_symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_symbol", "trade_date", "sequence_no", name="uix_broker_trade_daily"
        ),
    )
    op.create_table(
        "broker_trade_watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "stock_symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_symbol"],
            ["stocks.stock_symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("broker_trade_watchlist")
    op.drop_table("broker_trade_daily")
    # ### end Alembic commands ###
