"""change column type to not nullable

Revision ID: 61d64d7c076d
Revises: e0aafc8e3ac1
Create Date: 2025-01-28 16:53:57.784454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "61d64d7c076d"
down_revision: Union[str, None] = "e0aafc8e3ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_share_distribution",
        "stock_symbol",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "stock_share_distribution", "date_time", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "stock_share_distribution",
        "holding_order",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_share_distribution",
        "holding_order",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "stock_share_distribution", "date_time", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "stock_share_distribution",
        "stock_symbol",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###
