"""init

Revision ID: e0aafc8e3ac1
Revises:
Create Date: 2025-01-21 14:44:28.761412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0aafc8e3ac1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_list",
        sa.Column("stock_symbol", sa.String(length=20), nullable=False),
        sa.Column("stock_name", sa.UnicodeText(), nullable=True),
        sa.Column("last_updated_at", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("stock_symbol"),
    )
    op.create_table(
        "stock_share_distribution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_symbol", sa.String(length=20), nullable=True),
        sa.Column("date_time", sa.Date(), nullable=True),
        sa.Column("holding_order", sa.Integer(), nullable=True),
        sa.Column("number_of_holder", sa.Integer(), nullable=True),
        sa.Column("shares", sa.BIGINT(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_symbol"],
            ["stock_list.stock_symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_symbol", "date_time", "holding_order", name="uix_stock_distribution"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_share_distribution")
    op.drop_table("stock_list")
    # ### end Alembic commands ###
