- repo: local
  hooks:
    - id: export-requirements
      name: Export requirements.txt using poetry
      entry: poetry export -f requirements.txt \
            --output src/dashboard/requirements.txt \
            --extras dashboard --without-hashes\
            && poetry export -f requirements.txt \
            --output src/crawler/requirements.txt \
            --extras crawler --without-hashes
      language: system
      files: ^pyproject.toml$