services:
  streamlit:
    build:
      context: .
      dockerfile: ./src/dashboard/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_BROWSER_SERVER_ADDRESS="localhost"
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    env_file:
      - .env
    depends_on:
      - db

  crawler:
    build: 
      context: .
      dockerfile: ./src/crawler/Dockerfile
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - db
      - prefect-server
    command: >
      /bin/sh -c "
      cd /app/database && alembic upgrade head && cd ..;
      echo 'start Crawler...';
      python crawler/main.py;"

  prefect-server:
    image: prefecthq/prefect:3-latest
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_HOST=0.0.0.0
      - PREFECT_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=${PREFECT_UI_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/prefect
    command: prefect server start --host 0.0.0.0
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
        - ${PWD}/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
        - "5432:5432"

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_REQUEST_TIMEOUT=500