services:
  streamlit:
    build:
      context: .  # 將上下文設為 src 目錄
      dockerfile: ./src/dashboard/Dockerfile  # 指定 Dockerfile 的位置
    ports:
      - "8501:8501"  # 映射端口
    environment:
      - STREAMLIT_BROWSER_SERVER_ADDRESS="localhost"
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    env_file:
      - .env
    depends_on:
      - db
  crawler:
    build: 
      context: .
      dockerfile: ./src/crawler/Dockerfile
    ports:
      - "4200:4200"  # 映射端口
    env_file:
      - .env
    depends_on:
      - db
    command: >
      /bin/sh -c "
      cd /app/database && alembic upgrade head && cd ..;
      echo 'start Prefect Server and Crawler...';
      prefect server start --host 0.0.0.0 & python crawler/main.py;
      wait"
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
        - postgres_data:/var/lib/postgresql/postgres
    expose:
      - 5432
    ports:
        - "5433:5432"
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

volumes:
  postgres_data: